[tools]
node = "latest"
overmind = "latest"
oxfmt = "latest"

[env]
PGDATABASE = "fastify_blog_dev"
DATABASE_URL = "postgres://postgres:postgres@localhost/{{ env.PGDATABASE }}"

# openssl genpkey -algorithm ed25519
JWT_SIGNER_PRIVATE_KEY = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMaGlXeE5mbjRXMVoxUzFzMEI5T08yQ0ZxTFFQRWw4M1I1a0JzRDRXdDJNCnkzelpocUVZUWlCNjZaeDkxRGxVRWZkTEplVURDdGxVNytJTldhb252WVkKLT4gc3NoLWVkMjU1MTkgc0dxOUN3IGV2UjJiSjF3Zmw0SDg3MzhpOFVCYnplYlJrUkZlYkZ0QTVaSmVKTUtmd1UKQTE2Vm9yRDREY1ErREZuUC9EcUpVSXR3d1FmdG13UDRqUzV4Um5vY21YOAotPiBzc2gtcnNhIHNmK21WdwppMjhuY3VhK29rRGlFZHVmSUh1SW9NTFVlb0VxZjhOVC8za0hWS3BUTWZMQVV6WW5scWZkUm9OOFhYc0F0eTZvCkQ2QjREZ1M0YTZILy8vNzdkQ2dXNlVITWJacmxiNmlrZHd4U2Q5cnBZRTR0dHU5TDFnRjVsMTNmSTBiNUpDNk8KRE9YaFp2bjIrKzY2ektWNUttL1E5R0lzNWRNR0FOZ1Y4UDdNdXZmQUJXRXp3VkJnNzBjWUpDVXJHekY1RTQ3SAoraTVZbnk4anpsR29aZWxLZlAxcThmdTc5L2xJaHhCZ2xwL2Q2UFIyZWJuRE9VQVora1pnbG9WMndaaURucU1yCmUrRVJ5cnRHbHQ5MmVsbW8vNUZ3UDVoTWNOQUJ0Snkyajg3ZjFkNmFxemxsVEZHNnE5NWpFWFBLdHN1c2hjci8KQVpXWGt6L01WYzlzclBpZDFKaGtJQQotPiBWeV14XywyLWdyZWFzZSBaQlglXUk/ewpHWFlRYVdldlNGaklFK2pVKzdBZ3k1MHZlMzFIenJVbFNxUHQ4U3JHdVJkNkNnSHdMS3pxUEdPVSsydjJ4ZDNwClAvNXVpRUxudFkvYWFmZTJTdwotLS0gZ0owUVJ6VzgyS3BGbDFnU2FPZ2l0VS93ckk5Nm5XMVE4ZEhMRjdKUGZZWQoZeUqs34XNTxe40MIIw/dJHxt8lZCWHkV8qZsZ/H9E7qpG+14w84U792W4aHi3+qvwdVRCXAEHxjN4g4rFiDwA0GwI34altOYjxQGf6ER0FO3dYVKIcTRguftsmUNipSxQCwjQt1e1h/17fcNnp5ZI6Xp5ZBdrFng2kaKHOppoJ8lFCe6diA5+UuPrR2CWVHNtEcigyPc" }

# echo $priv_key | openssl pkey -pubout
JWT_SIGNER_PUBLIC_KEY = """
-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEA1ZlSI3q84U3Wi9uHjp2JvZ9O8kqLoC5Tmi7vRpKXo8Q=
-----END PUBLIC KEY-----"""
