[tools]
node = "latest"
overmind = "latest"
oxfmt = "latest"

[env]
PGDATABASE = "fastify_blog_dev"
DATABASE_URL = "postgres://postgres:postgres@localhost/{{ env.PGDATABASE }}"

# openssl genpkey -algorithm ed25519
JWT_SIGNER_PRIVATE_KEY = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UndFQTJWcVdPRmpndkljTVhoL3dBZldkblNyQXlEbzZYNDlwbGpVNlVZCjQ0VmRCZTNXVU1KYjRBdWI2Q2FOcm44ckVHYWVQVFA0MWdoQzdJdWVBOXcKLT4gc3NoLWVkMjU1MTkgc0dxOUN3IFlQUXpkY0djRkJMVDZSbFhOQ25QWDM4ODc4ZEVjOVJVcTlacEc4RlJBd0kKWlJkQ25HdFZqQlpxNkc3ZWVXcVZwSDMxZ2lab2F4Y1dyazFPOS94a0w5SQotPiBzc2gtcnNhIHNmK21WdwpXZ2tZNWhLQmZTT2lqQUYyTzhOeGVtUGNkQkhGMXpRSVBET3lTT0Qwb0ljL1J4RWp4OGNuMkVEN21wcTVCZFJsCmRFNzVkQ2haTjgybmFXczB2ZGJBRU1BUlVLdHBDejBsdnMxejJDcDVLTjduZXQzcEJxd0J3c0t1aFZxSWlJQ04KZ0YrTmdidU1sSE91bmJvSEVWUzVnZkF4UDhXRGVxQ3c5c0lUY1I5cVE2SW9xcFRwS01nRVd3R3AwUFR4dlFzNApydXZ4VnNvWWhiL0FXV0JUU2F5T3d3dUdia1J0TGRSUWlmektiSUl1S29BNzM2TlppQkUyMkdIY0I1VGwvSytVClYzWWdodVRmSGFHZHhqZGZIVmdFbm1HemxUOTN1SzVzTFR0S0VGNGcrZTR2Yy9HckhuRjR6QXRMeVhpekcrZEcKK0MwdHI2d2tDM3IwVDMzTUpVVFZUdwotPiBjcE9vbkYtZ3JlYXNlIHZVQW0KZjQ1SFRXeFNMdmRoU3pUZWUrVnpGbVg4SVVPb0VKeTMzRUpxCi0tLSA4Q2dkTTNWVGx3eVA2YnVwV2xoY25vZlluMnhFcVg3c1hrME1XdzNPeHRzCnVLKhM6k/u1fKKyONTFFMfGMVTastXz73IfXzj7CDjxs9+CnOJ9cHL6sdI+18tGVMf4b1keR5V1kTMyavJHQudI5jPgY06X0kIeFkS4qpPJC7SZbfY5ZVkv+HhXvQHk1KqLQ6Qy+TCy3Y3VoNqKY9kcCC/J3eKZaKb50WJg0NiGo0plbvaY/n85oacHLn8SUiK0si/gBw" }

# echo $priv_key | openssl pkey -pubout
JWT_SIGNER_PUBLIC_KEY = """
-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEA1ZlSI3q84U3Wi9uHjp2JvZ9O8kqLoC5Tmi7vRpKXo8Q=
-----END PUBLIC KEY-----"""
